---
 - name: install apache
   yum:  
      name: "{{ item }}" 
      state: latest
   with_items: "{{apache_packages}}"
    
 - name: start httpd
   service: name=httpd state=started enabled=yes
  
 - name: Open firewall 
   shell: firewall-cmd --set-default-zone=public && firewall-cmd --permanent --zone=public --add-service=http && firewall-cmd --permanent --zone=public --add-port=80/tcp && firewall-cmd --reload

 - name: ADD phpinfo
   copy: 
    src: index.php
    dest: /var/www/html/index.php
   notify: restart apache 
   
