---
 - name: Add Yum Repositories
   yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present

 - name: Install phpmyadmin packages
   yum: name={{ item }}  enablerepo=remi-php70 state=present
   with_items:
       - php
       - phpmyadmin
       - php-mysql
       
# tasks for phpmyadmin

 - name: Install EPEL Repo
   yum: name=epel-release state=installed
  
 - name: Install PhpMyAdmin
   yum: name=phpmyadmin state=latest enablerepo=epel
  
 - name: Copy PhpMyAdmin Config Files
   shell: /usr/bin/sed -i s/'cookie'/'http'/g /etc/phpMyAdmin/config.inc.php  

 - name: Copy PhpMyAdmin Appache Config Files
   copy: src=phpMyAdmin.conf dest=/etc/httpd/conf.d/phpMyAdmin.conf owner=root group=root mode=0775
   notify: restart apache 
